### ISSUE TITLE
[Feature Request] Multi-user (groups)

### ISSUE THREAD

**Issue by couleurm** [AndyRusso/msg-lock#1]
Be able to /msglock \<user1> \<user2> and if they do it as well have some kind of a party/faction chat 

Now that I write it I realize it could be useful for very heavy spam but if you do it for a few users and the servers doesn't mind it 🤷‍♂️

**Comment by AndyRusso** [comment]
Hello.
Funny story: I considered this feature back in October, and the conclusion was I should test if players are allowed to send a couple of instant messages on servers, and if yes, then add it as a planned feature, but I never tested it.
Now I did, `pvplegacy.net` and `hypixel.net` don't allow that, it's fine on `mccisland.net` and `mcpvp.club`, but I think those big servers are a good enough reason to not make it.
Yes, I could add an internal timeout, but that's inherently malicious.

Closing as not planned.
